---
- hosts: all
  become: true

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted


  tasks:
    - name: Ensure Apache is installed.
      package:
        name: apache2
        state: present
    - name: Copy a web page.
      copy:
        content: |
          <html>
          <head><title>Hello world!</title></head>
          <body>Hello World!</body>
          </html>
        dest: "/var/www/html/index.html"
        mode: 0644
      notify: restart apache

    - name: Ensure Apache is running and starts at boot.
      service:
        name: apache2
        state: started
        enabled: true
